### PR TITLE
Sortingoutthosedamntextboxes

### PR DESCRIPTION
**Pull request by Mbjoerkh**
RA Proofreading Complete

### CODE REVIEW

**Comment by Vandivier** [comment]
@Mbjoerkh please adopt master's package.json as it is conflicted:

**Comment by Mbjoerkh** [comment]
Done (I think...)

**Comment by Vandivier** [comment]
are you looking at this pull request page? https://github.com/Vandivier/data-science-practice/pull/11

there is one line left in conflict because the indentation differs

**Comment by Mbjoerkh** [comment]
My bad. Didn't see the diff bt tab and spaces when looking in notepad..

**Pull request merged**
